apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sample-html-template
  title: Sample HTML Website
  description: Creates a basic HTML page
spec:
  owner: user:guest
  type: website

  parameters:
    - title: Website Info
      required: [name]
      properties:
        name:
          title: Website Name
          type: string
          description: Name of your website

  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.fetch.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: View Website
        url: ${{ steps.fetch.output.remoteUrl }}
