apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-form-template
  title: My Form Template
  description: A template for creating a form
spec:
  owner: user:default/prakashsbanu12
  type: service
  parameters:
    - title: Fill out the details
      required:
        - component_name
      properties:
        component_name:
          title: Name
          type: string
          description: Unique name of the component
  steps:
    - action: debug:log
      name: Log the component name
      input:
        message: Creating component ${{ parameters.component_name }}
