apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: my-form-template
  title: My Custom Form Template
  description: A template that collects user input and performs an action
spec:
  owner: user:guest
  type: form

  parameters:
    - title: Project Info
      required:
        - projectName
        - ownerName
      properties:
        projectName:
          title: Project Name
          type: string
          description: Name of your project
        ownerName:
          title: Owner Name
          type: string
          description: Who owns this project?
        repoUrl:
          title: GitHub Repo URL
          type: string
          description: Link to your GitHub repository
        environment:
          title: Environment
          type: string
          enum:
            - dev
            - staging
            - prod
          default: dev
          description: Choose the deployment environment

  steps:
    - id: log-input
      name: Log Input
      action: debug:log
      input:
        message: |
          Received input:
          Project Name: ${{ parameters.projectName }}
          Owner: ${{ parameters.ownerName }}
          Repo: ${{ parameters.repoUrl }}
          Environment: ${{ parameters.environment }}

    - id: create-file
      name: Create Config File
      action: fs:write
      input:
        path: ./output/config.json
        content: |
          {
            "projectName": "${{ parameters.projectName }}",
            "ownerName": "${{ parameters.ownerName }}",
            "repoUrl": "${{ parameters.repoUrl }}",
            "environment": "${{ parameters.environment }}"
          }

  output:
    links:
      - title: View Output File
        url: ./output/config.json
