---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: A sample web service for Backstage
  annotations:
    github.com/project-slug: your-username/backstage-catalog
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team:engineering
  providesApis:
    - my-service-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-service-api
  description: API for the sample web service
spec:
  type: openapi
  lifecycle: experimental
  owner: team:engineering
  definition:
    $text: ./openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  description: Engineering team
spec:
  type: team
  profile:
    displayName: Engineering Team
    email: engineering@example.com
  children: []
