apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: host-form-template
  title: Host Form Template
  description: A simple form to collect host details
spec:
  type: form
  owner: user:guest
  parameters:
    - title: Host Query Input
      required:
        - hostnames
        - proposedSchedule
      properties:
        hostnames:
          type: array
          title: Hostnames
          description: List of hostnames to query
          items:
            type: string
        proposedSchedule:
          type: string
          title: Proposed Schedule
          default: "TBD"
          description: Enter the proposed schedule (e.g., 2025-08-15 14:00)

  steps:
    - id: log-input
      name: Log Input
      action: debug:log
      input:
        message: |
          Hostnames: ${{ parameters.hostnames }}
          Schedule: ${{ parameters.proposedSchedule }}
