apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: host-form-template
spec:
  parameters:
    - title: Host Input
      required: ['hostname', 'source']
      properties:
        hostname:
          type: string
        source:
          type: string
          enum: ['api', 'excel']
        excelPath:
          type: string
          default: ./plugins/scaffolder-backend/actions/host-lookup/sample.xlsx

  steps:
    - id: lookup
      name: Lookup Host Info
      action: custom:host-lookup
      input:
        hostname: ${{ parameters.hostname }}
        source: ${{ parameters.source }}
        excelPath: ${{ parameters.excelPath }}

    - id: use-data
      name: Use Host Data
      action: debug:log
      input:
        message: |
          Host Info: ${{ steps.lookup.output.hostData }}
