apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: server-reboot-from-cmdb
  title: Reboot Server (with CMDB Lookup)
  description: Safely reboot a server using details fetched from CMDB
  tags:
    - server
    - reboot
    - operations
    - cmdb
spec:
  owner: system:default/guest # Adjust as needed for your organization
  type: service
  parameters:
    - title: Server Identification
      required:
        - serverIdentifier
      properties:
        serverIdentifier:
          title: Server Name or Identifier
          type: string
          description: Enter the name or ID of the server to reboot (will be looked up in CMDB).
          ui:autofocus: true
          ui:options:
            rows: 2
    - title: Reboot Details
      required:
        - rebootReason
      properties:
        rebootReason:
          title: Reason for Reboot
          type: string
          description: Briefly explain why the server needs to be rebooted.
          ui:options:
            rows: 5
        scheduleAt:
          title: Schedule Reboot (Optional)
          type: string
          ui:field: DateTimePicker # This requires a custom field extension in your Backstage app
          description: Optionally schedule the reboot for a specific date and time.
  steps:
    - id: lookupServer
      name: Look up Server in CMDB
      action: cmdb:lookupServer # Calls your custom action for CMDB lookup
      input:
        serverIdentifier: ${{ parameters.serverIdentifier }}

    - id: confirmRebootDetails
      name: Confirm Server Details
      action: debug:log # This step logs the information fetched from CMDB for confirmation
      input:
        message: |
          Confirming reboot for server: ${{ outputs.lookupServer.serverName }}
          IP Address: ${{ outputs.lookupServer.ipAddress }}
          Environment: ${{ outputs.lookupServer.environment }}
          Owner: ${{ outputs.lookupServer.owner }}
          Reboot Reason: ${{ parameters.rebootReason }}
          Schedule: ${{ parameters.scheduleAt }}
          Proceeding with reboot...

    - id: rebootServer
      name: Perform Server Reboot
      action: server:reboot # Calls your custom action for server reboot
      input:
        serverName: ${{ outputs.lookupServer.serverName }} # Uses output from the CMDB lookup
        rebootReason: ${{ parameters.rebootReason }}
        environment: ${{ outputs.lookupServer.environment }} # Pass environment from CMDB
        scheduleAt: ${{ parameters.scheduleAt }} # Pass the optional schedule
