apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: host-form-template
  title: Host Form Template
  description: A simple form to collect host details and log them
spec:
  type: form
  owner: user:guest
  parameters:
    - title: Host Information
      required:
        - hostname
        - environment
      properties:
        hostname:
          type: string
          title: Hostname
          description: Enter the hostname of the server
        environment:
          type: string
          title: Environment
          description: Choose the deployment environment
          enum:
            - dev
            - staging
            - prod
          default: dev

  steps:
    - id: log-host-info
      name: Log Host Info
      action: debug:log
      input:
        message: |
          🖥️ Hostname: ${{ parameters.hostname }}
          🌐 Environment: ${{ parameters.environment }}

    - id: write-output
      name: Write Output File
      action: fs:write
      input:
        path: ./host-info.txt
        content: |
          Hostname: ${{ parameters.hostname }}
          Environment: ${{ parameters.environment }}

  output:
    links:
      - title: Download Host Info
        url: ./host-info.txt
