apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-registration
  title: User Registration Form
  description: Collect user info with date of birth
spec:
  owner: user-team
  type: form
  parameters:
    - title: User Info
      required: [name, dob]
      properties:
        name:
          title: Full Name
          type: string
          description: Enter your full name
          ui:autofocus: true

        dob:
          title: Date of Birth
          type: string
          format: date
          description: Select your date of birth
          ui:widget: date

  steps:
    - id: log
      name: Log User Info
      action: debug:log
      input:
        message: "User ${{ parameters.name }} was born on ${{ parameters.dob }}"
