apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: v1beta3-demo
  title: V1Beta3 Demo Template
  description: A demo template using v1beta3
spec:
  owner: user:guest
  type: service
  parameters:
    - title: Provide some information
      required:
        - name
      properties:
        name:
          type: string
          title: Name of the service
  steps:
    - id: fetch
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: https://github.com/some-org/some-repo/tree/main/template
        targetPath: ./workspace
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?repo=my-repo&owner=my-org
        title: ${{ parameters.name }}
        description: Scaffolded from Backstage
        visibility: public
