apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cmdb-query-template
  title: Query CMDB and Save to Excel
  description: Fetch host details from CMDB and export to Excel
spec:
  type: service
  owner: user:guest
  parameters:
    - title: Host Query Input
      required:
        - hostnames
        - proposedSchedule
      properties:
        hostnames:
          type: array
          title: Hostnames
          description: List of hostnames to query
          items:
            type: string
        proposedSchedule:
          type: string
          title: Proposed Schedule
          default: "TBD"
          description: Enter the proposed schedule (e.g., 2025-08-15 14:00)

  steps:
    - id: fetch-cmdb-data
      name: Fetch CMDB Data
      action: fetch:plain
      input:
        method: POST
        url: https://your-cmdb-api.example.com/query
        headers:
          Authorization: Basic ${{ secrets.cmdb_auth }}
          Content-Type: application/json
        body: |
          {
            "hostnames": ${{ parameters.hostnames }},
            "schedule": "${{ parameters.proposedSchedule }}"
          }
        output: cmdbResponse

    - id: log-response
      name: Log CMDB Response
      action: debug:log
      input:
        message: "CMDB Response: ${{ steps.fetch-cmdb-data.output.body }}"

    - id: save-to-excel
      name: Save to Excel
      action: custom:saveExcel
      input:
        data: ${{ steps.fetch-cmdb-data.output.body }}
        filename: cmdb_output.xlsx

  output:
    links:
      - title: CMDB Excel Output
        url: ./cmdb_output.xlsx
