apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: user-registration
  title: User Registration Form
  description: Collect user info with date of birth and timestamp
spec:
  owner: user-team
  type: form
  parameters:
    - title: User Info
      required: [name, dob]
      properties:
        name:
          title: Full Name
          type: string
          description: Enter your full name
          ui:autofocus: true

        dob:
          title: Date of Birth
          type: string
          format: date
          description: Select your date of birth
          ui:widget: date

  steps:
    - id: get-time
      name: Get Current DateTime
      action: fetch:plain
      input:
        url: https://worldtimeapi.org/api/timezone/Asia/Kolkata
        method: GET
        headers:
          Accept: application/json

    - id: log
      name: Log User Info
      action: debug:log
      input:
        message: |
          User: ${{ parameters.name }}
          Date of Birth: ${{ parameters.dob }}
          Submitted At: ${{ steps['get-time'].output.datetime }}
