apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cmdb-host-registration
  title: Register Host via CMDB
  description: Queries ServiceNow CMDB and generates catalog-info.yaml
spec:
  owner: banu
  type: service
  parameters:
    - title: Host Input
      required: [hostname]
      properties:
        hostname:
          type: string
          title: Hostname
          description: Enter the host name to query CMDB
  steps:
    - id: cmdb-query
      name: Query CMDB
      action: banu:cmdb:query-host
      input:
        hostname: ${{ parameters.hostname }}

    - id: generate-yaml
      name: Generate catalog-info.yaml
      action: banu:cmdb:generate-yaml
      input:
        hostname: ${{ parameters.hostname }}
        owner: ${{ steps.cmdb-query.output.owner }}
        environment: ${{ steps.cmdb-query.output.environment }}
        schedule: ${{ steps.cmdb-query.output.schedule }}
        proposed_window: ${{ steps.cmdb-query.output.proposed_window }}
