apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cmdb-host-registration
  title: Register Host via CMDB
  description: Queries CMDB and generates catalog-info.yaml via GitHub workflow
spec:
  owner: banu
  type: service
  parameters:
    - title: Host Input
      required: [host_name]
      properties:
        host_name:
          type: string
          title: Host Name
          description: Enter the hostname to query CMDB
  steps:
    - id: trigger-cmdb-workflow
      name: Trigger GitHub Workflow
      action: github:actions:dispatch
      input:
        repoUrl: github.com?repo=banu/cmdb-host-registration
        workflowId: cmdb-register.yaml
        workflowInputs:
          host_name: ${{ parameters.host_name }}
