apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: cmdb-dynamic-form
  title: CMDB Dynamic Form Loader
  description: Enter host name, fetch CMDB data, and prefill form

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Step 1: Host Info
      required: [hostName]
      properties:
        hostName:
          type: string
          title: Host Name
          description: Enter the hostname to query CMDB

  steps:
    - id: fetch-cmdb
      name: Fetch CMDB Data
      action: fetch:plain
      input:
        url: https://your-cmdb-api/components/${{ parameters.hostName }}
        method: GET

    - id: write-form
      name: Prefill Metadata Form
      action: fs:write
      input:
        path: metadata-form.json
        content: |
          {
            "name": "${{ parameters.hostName }}",
            "owner": "${{ steps.fetch-cmdb.output.ownedBy }}",
            "environment": "${{ steps.fetch-cmdb.output.environment }}",
            "calendar": "${{ steps.fetch-cmdb.output.calendar }}",
            "proposedDate": "${{ steps.fetch-cmdb.output.proposedDate }}"
          }

    - id: generate-catalog
      name: Generate catalog-info.yaml
      action: fs:write
      input:
        path: catalog-info.yaml
        content: |
          apiVersion: backstage.io/v1alpha1
          kind: Component
          metadata:
            name: ${{ parameters.hostName }}
            description: Loaded from CMDB
            annotations:
              cmdb.io/calendar: ${{ steps.fetch-cmdb.output.calendar }}
              cmdb.io/proposed-date: ${{ steps.fetch-cmdb.output.proposedDate }}
          spec:
            type: service
            lifecycle: production
            owner: ${{ steps.fetch-cmdb.output.ownedBy }}
            environment: ${{ steps.fetch-cmdb.output.environment }}

    - id: register
      name: Register in Catalog
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/prakashsbanu12/backstage-catalog
        catalogInfoPath: catalog-info.yaml

  output:
    text:
      - title: Component Registered
        content: Host ${{ parameters.hostName }} registered with CMDB metadata
