apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: query-host
  title: Query Host from CMDB
  description: Fetches host details from ServiceNow CMDB
spec:
  owner: banu
  parameters:
    - title: Host Query
      required:
        - hostname
      properties:
        hostname:
          type: string
          title: Hostname
  steps:
    - id: query-host
      name: Query Host
      action: banu:servicenow:query-host
      input:
        hostname: ${{ parameters.hostname }}
